CREATE TABLE IF NOT EXISTS words (
        definition text DEFAULT ''::text NOT NULL,
        length integer DEFAULT 0 NOT NULL,
        numofa integer DEFAULT 0,
        numofb integer DEFAULT 0,
        numofc integer DEFAULT 0,
        numofd integer DEFAULT 0,
        numofe integer DEFAULT 0,
        numoff integer DEFAULT 0,
        numofg integer DEFAULT 0,
        numofh integer DEFAULT 0,
        numofi integer DEFAULT 0,
        numofj integer DEFAULT 0,
        numofk integer DEFAULT 0,
        numofl integer DEFAULT 0,
        numofm integer DEFAULT 0,
        numofn integer DEFAULT 0,
        numofo integer DEFAULT 0,
        numofp integer DEFAULT 0,
        numofq integer DEFAULT 0,
        numofr integer DEFAULT 0,
        numofs integer DEFAULT 0,
        numoft integer DEFAULT 0,
        numofu integer DEFAULT 0,
        numofv integer DEFAULT 0,
        numofw integer DEFAULT 0,
        numofx integer DEFAULT 0,
        numofy integer DEFAULT 0,
        numofz integer DEFAULT 0,
        word text NOT NULL
);
