
services:
  db:
    image: postgres:alpine
    build: src/database_creation
    container_name: db
    expose:
      - "5432:5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scrabble
      PGDATA: /data/postgres

    restart: always
  app:
    build: .
    expose:
      - "8080:8080"
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=scrabble
      - POSTGRES_PASSWORD=password
    depends_on:
      - db

