
services:
  db:
    image: mydb:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scrabble
      PGDATA: /data/postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  app:
    image: app:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy



