
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scrabble
      PGDATA: /data/postgres

    restart: always
  app:
    image: words:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db

