services:
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - "5432:5432"
    expose:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scrabble
      PGDATA: /data/postgres

    restart: always

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    expose:
      - "8080:8080"
    environment:
      - POSTGRES_DB=scrabble
      - POSTGRES_PASSWORD=password
    depends_on:
      - db





