
services:
  db:
    image: postgres:alpine
    build: ScrabbleDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scrabble
      PGDATA: /data/postgres

    restart: unless-stopped

#  app:
#    build: .
#    ports:
#      - 8080:8080
#    environment:
#      - POSTGRES_DB=scrabble
#      - POSTGRES_PASSWORD=password
#    depends_on:
#      - db




