spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: scrabble

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes

wordsfornerds:
  url: jdbc:postgresql://127.0.0.1:5432/scrabble # maybe unneeded but change host if required when publishing

